language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install cython numpy scipy pytest
  - sudo apt-get install build-essential swig
  - pip install git+https://github.com/herilalaina/mosaic@0.1
  - pip install git+https://github.com/herilalaina/mosaic_ml
# command to run tests
script:
  - pytest
