theme: jekyll-theme-cayman
title: Automated Machine Learning with Monte-Carlo Tree Search
description: Mosaic ML is a Python library for machine learning pipeline configuration using Monte Carlo Tree Search.
